const depcheck = require('depcheck');

/** @type {import('depcheck').Options} */
module.exports = {
  ignoreMatches: [
    '@vitest/coverage-v8',
    '@axe-core/react',
    '@eslint/js',
    '@size-limit/file',
    'autoprefixer',
    'eslint',
    'eslint-config-next',
    'eslint-plugin-jsx-a11y',
    'fast-check',
    'globals',
    'husky',
    'jest-axe',
    'knip',
    'lint-staged',
    'madge',
    'playwright',
    'postcss',
    'prettier',
    'prettier-plugin-tailwindcss',
    'size-limit',
    'ts-prune',
    'typescript',
    'typescript-eslint',
    'vitest-axe',
  ],
  ignores: [
    '@vitest/coverage-v8',
    '@axe-core/react',
    '@eslint/js',
    '@size-limit/file',
    'autoprefixer',
    'eslint',
    'eslint-config-next',
    'eslint-plugin-jsx-a11y',
    'fast-check',
    'globals',
    'husky',
    'jest-axe',
    'knip',
    'lint-staged',
    'madge',
    'playwright',
    'postcss',
    'prettier',
    'prettier-plugin-tailwindcss',
    'size-limit',
    'ts-prune',
    'typescript',
    'typescript-eslint',
    'vitest-axe',
  ],
  specials: [
    depcheck.special.eslint,
    depcheck.special.prettier,
    depcheck.special.typescript,
    depcheck.special.bin,
  ],
};
